### ISSUE TITLE
Network connection timeout error when the search has no results.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1662]
**Describe the bug**
Instead of getting "No search results that match the query" error message, we get Network connection timed out.

**To Reproduce**
1. Go to home page
2. Set the search type to main letters
3. Add few random letters, that doesn't make a word like `ddsa`
4. Instead of getting no search results, it shows Network connection timeout
5. See error

**Screenshots**
![image](https://github.com/KhalisFoundation/sttm-web/assets/1990932/13be586a-1c59-46fe-9ea1-aefdf7f57505)

**Comment by gurjit03** [comment]
Seems the problem has been fixed. Please reopen this when you still sees the issue
<img width="1512" alt="image" src="https://github.com/KhalisFoundation/sttm-web/assets/8514802/8743f5c8-0741-4a68-a0b9-ffb0cf1674a5">

**Comment by Gauravjeetsingh** [comment]
<img width="1448" alt="image" src="https://github.com/KhalisFoundation/sttm-web/assets/1990932/b47a1cf6-d9fa-4027-ab8f-8a5231b8e474">
Still happening for me. 

I believe this happens, when the source is set to All sources.

**Comment by gurjit03** [comment]
@Gauravjeetsingh Interesting enough I did get network error the first time I tried and then I could see the search results properly on the 2nd time. Seems to me the issue with API returning the results.

<img width="750" alt="image" src="https://github.com/KhalisFoundation/sttm-web/assets/8514802/b7151906-b06c-4c6d-accc-e04e4fce6067">

I will still do more diagnoses of this problem to reach a proper conclusion.

**Comment by gurjit03** [comment]
@Gauravjeetsingh are you still facing this error?

**Comment by Gauravjeetsingh** [comment]
@gurjit03 veerji, yeah its working now, getting no results found error instead of network connection timeout. Tried with multiple search keywords.

**Comment by gurjit03** [comment]
I am closing this issue then
